### ISSUE TITLE
Do not find a title

### ISSUE THREAD

**Issue by lcaleixo** [mancuniancol/script.magnetic.eztv-mc#1]
I'm starting to see the series the tudors .. and I noticed that the title exists on the eztv page, but it does not return the result if it searches for the provider. Example: the tudors s01e06 exists on the eztv page .. But if I go through the quasar and its provider it does not return the result .. any help?!? Sorry for English. Google translator.

**Comment by mancuniancol** [comment]
I need your kodi log in debug mode

**Comment by mancuniancol** [comment]
I've checked the page and the format is not S00E00, but instead 0x00.  Then you need to add the format in the settings of the provider.
{title} {season}x{episode:2}

**Comment by mancuniancol** [comment]
I've tested and it is working.  I will close this issue, because it's fixed with proper settings.

**Comment by lcaleixo** [comment]
thank you!!!
